export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAILURE = 'RECIPE_LIST_FAILURE';
export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST';
export const RECIPE_DETAILS_SUCCESS = 'RECIPE_DETAILS_SUCCESS';
export const RECIPE_DETAILS_FAILURE = 'RECIPE_DETAILS_FAILURE';